### ISSUE TITLE
What is the status of this project? 

### ISSUE THREAD

**Issue by codekiln** [closeio/mongoengine#18]
It appears that there has not been much activity on this project lately. Is this project going to be abandoned?

**Comment by wojcikstefan** [comment]
@codekiln we plan to integrate our performance tweaks into the upstream repo (github.com/mongoengine/mongoengine) and phase out our own fork over time. That said, some major bug fixes might be applied to this repo on a per-need basis.

**Comment by decklord** [comment]
Is this already integrated into mongoengine?

**Comment by wojcikstefan** [comment]
Not yet, though moving in that direction. I'll post updates about the progress on this ticket.

**Comment by codekiln** [comment]
@wojcikstefan I'm just checking back in here to again see about the status. I love the idea of a lazily instantiated mongoengine. Any updates?

**Comment by cansar** [comment]
I have the same question. It seems like you guys are still actively developing this. Is there anything a MongoEngine user can do to help with getting this integrated?

**Comment by philfreo** [comment]
We're still using this project at Close. We do intend to eventually merge this project back into the upstream mongoengine, but that will be a good amount of work and we don't really have a timeline for that yet.

Two related issues from Upstream that will need to be resolved first (by us or the community):
- https://github.com/MongoEngine/mongoengine/issues/357
- https://github.com/MongoEngine/mongoengine/pull/2101

We have done more technical planning for this internally, and at some point @wojcikstefan will probably share a broader plan / try to be more transparent about what other blockers we have and see if anyone wants to help. But there's no timeline we can share for that, yet.

**Comment by neob91-close** [comment]
Is integrating this repo still planned, or has something changed?

**Comment by wojcikstefan** [comment]
No, the integration of this repo and the upstream MongoEngine is not planned anymore. I apologize for the delayed response and for the false sense of direction.

While looking into it, I've realized the two repos have diverged beyond the time/effort I can put into their reintegration. Some of the design decisions are in direct conflict and would lead to a painful set of breaking changes, too (e.g. how this repo has lazy `ReferenceField`s by default but in upstream there's a special `LazyReferenceField` class).

Overall, the community should focus on investing in the upstream version of MongoEngine and fix any performance issues & bugs in there directly. I invite y'all to take inspiration from this fork, but it's not like we'll magically copy over its solutions.
